name: snappable
description: A Flutter library for Thanos snap effect. Use it to turn your Widgets into dust. For fun only!
version: 1.1.0
author: Marcin Szałek <marcinszalek1@gmail.com>
homepage: https://github.com/MarcinusX/snappable

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
